# Lab Assignment: Building a Neural Network from Scratch

### Objective
This lab guides you through the implementation of a simple feedforward neural network from scratch. 
By completing this lab, you will:
- Initialize a neural network with weights and biases.
- Compute the weighted sum at each node.
- Apply activation functions for node outputs.
- Perform forward propagation to compute predictions.
- Implement backpropagation to compute gradients.
- Update weights using gradients to minimize the loss.

## Step 1: Initialize the Network

In [3]:
import numpy as np
np.random.seed(42) # For reproducibility
def initialize_network(input_size, hidden_layers, output_size):
    # Your code should contain the weights and biases
    # provide your code
    network = {}
    layer_sizes = [input_size] + hidden_layers + [output_size]  #combine all layers
    
    for i in range(len(layer_sizes) - 1):
        network[f'weights{i+1}'] = np.random.randn(layer_sizes[i+1], layer_sizes[i])  #random weights
        network[f'biases{i+1}'] = np.zeros((layer_sizes[i+1], 1))  #bias initialized to zero
    
    return network
 
    

# Initialize a network with 3 inputs, 2 hidden layers (4 and 3 nodes), and 1 output node
network = initialize_network(3, [4, 3], 1)
print("Cole Manchester + Initialized Network:", network)

Cole Manchester + Initialized Network: {'weights1': array([[ 0.49671415, -0.1382643 ,  0.64768854],
       [ 1.52302986, -0.23415337, -0.23413696],
       [ 1.57921282,  0.76743473, -0.46947439],
       [ 0.54256004, -0.46341769, -0.46572975]]), 'biases1': array([[0.],
       [0.],
       [0.],
       [0.]]), 'weights2': array([[ 0.24196227, -1.91328024, -1.72491783, -0.56228753],
       [-1.01283112,  0.31424733, -0.90802408, -1.4123037 ],
       [ 1.46564877, -0.2257763 ,  0.0675282 , -1.42474819]]), 'biases2': array([[0.],
       [0.],
       [0.]]), 'weights3': array([[-0.54438272,  0.11092259, -1.15099358]]), 'biases3': array([[0.]])}


## Step 2: Compute Weighted Sum

In [5]:
def compute_weighted_sum(inputs, weights, biases):
    # Please numpy dot to calcuate the compute weighted with linear 
    # provide your code
    return np.dot(inputs, weights.T) + biases
    #use numpy dot function
    
    
network = {
    'weights': np.random.randn(4, 3),  # 4 neurons, 3 input features
    'biases': np.zeros((4, 1))         # 4 neurons, 1 bias per neuron
}#test for the sum values

# Test weighted sum
inputs = np.array([[0.5, 0.2, 0.1]])
layer = network   #set as dictionary so no [0] needed  # First layer
Z = compute_weighted_sum(inputs, layer['weights'], layer['biases'])
print("Cole + Weighted Sum:", Z)

Cole + Weighted Sum: [[ 0.0385519   0.06825261 -0.48643085 -0.42032083]
 [ 0.0385519   0.06825261 -0.48643085 -0.42032083]
 [ 0.0385519   0.06825261 -0.48643085 -0.42032083]
 [ 0.0385519   0.06825261 -0.48643085 -0.42032083]]


## Step 3: Compute Node Activation

In [35]:
def sigmoid(Z):
#     provide your code
    return 1/(1+np.exp(-Z))

def sigmoid_derivative(A):
    # provide your code
    return A*(1-A)

# Compute activation for the weighted sum
A = sigmoid(Z)
print("Cole + Activation:", A)

Cole + Activation: [[0.50963678 0.51705653 0.38073473 0.39643998]
 [0.50963678 0.51705653 0.38073473 0.39643998]
 [0.50963678 0.51705653 0.38073473 0.39643998]
 [0.50963678 0.51705653 0.38073473 0.39643998]]


## Step 4: Perform Forward Propagation

In [85]:
def forward_propagation(inputs, network):
    activations = [inputs]  
    current_input = inputs
    layer_num = 1  #  tracks the layer number
    while f'weights{layer_num}' in network and f'biases{layer_num}' in network:
        weights = network[f'weights{layer_num}']
        biases = network[f'biases{layer_num}']
        Z = compute_weighted_sum(current_input, weights, biases)
        A = sigmoid(Z)  #our activation funct
        activations.append(A)
        current_input = A
        layer_num += 1  # increment layer number

    return activations



# Perform forward propagation
activations = forward_propagation(inputs, network)
print(activations)
print("Cole + Final Output:", activations[-1])

[array([[0.5, 0.2, 0.1]])]
Cole + Final Output: [[0.5 0.2 0.1]]


## Step 5: Backpropagation

In [188]:
def backpropagation(network, activations, y_true):
    gradients = {}
    num_layers = len(network)

    delta = (y_true - activations[-1]) * sigmoid_derivative(activations[-1])
    layer_name = list(network.keys())[-1]
    gradients[layer_name] = {'dW': np.dot(activations[-2].T, delta), 'db': np.sum(delta, axis=0, keepdims=True)}

    for l in reversed(range(num_layers - 1)):
        layer_name = list(network.keys())[l]
        delta = np.dot(delta, network[list(network.keys())[l+1]]['weights'].T) * sigmoid_derivative(activations[l+1])

        print("Shape of activations[l].T:", activations[l].T.shape)  # Debug print
        print("Shape of delta:", delta.shape)                     # Debug print
        gradients[layer_name] = {'dW': np.dot(activations[l].T, delta), 'db': np.sum(delta, axis=0, keepdims=True)}

    return gradients

# Compute gradients
y_true = np.array([[1]])  # Example target output
gradients = backpropagation(network, activations, y_true)
print("Cole + Gradients:", gradients)

IndexError: list index out of range

## Step 6: Update Weights

In [168]:
def update_weights(network, gradients, learning_rate):
    # Hints: weights -= learning_rate * 'dW'
    # Hints: biases -= learning_rate * 'db'
    # Provide your code 
   for layer_name in network:
        if 'weights' in network[layer_name]:
            network[layer_name]['weights'] = np.array(network[layer_name]['weights'])  # convert to numpy array
            gradients[layer_name]['dW'] = np.array(gradients[layer_name]['dW']) # numpy array
            network[layer_name]['weights'] -= learning_rate * gradients[layer_name]['dW']
            network[layer_name]['weights'] = network[layer_name]['weights'].tolist() # make it back to a list
        if 'biases' in network[layer_name]:
            network[layer_name]['biases'] = np.array(network[layer_name]['biases']) # convert to numpy array
            gradients[layer_name]['db'] = np.array(gradients[layer_name]['db']) # Convert to numpy array
            network[layer_name]['biases'] -= learning_rate * gradients[layer_name]['db']
            network[layer_name]['biases'] = network[layer_name]['biases'].tolist() # convert back to a list another time


#my network I made up
network = {
    'layer1': {'weights': [[0.1, 0.2], [0.3, 0.4]], 'biases': [0.5, 0.6]},
    'layer2': {'weights': [[0.7, 0.8], [0.9, 1.0]], 'biases': [1.1, 1.2]}
}

gradients = {
    'layer1': {'dW': [[0.01, 0.02], [0.03, 0.04]], 'db': [0.05, 0.06]},
    'layer2': {'dW': [[0.07, 0.08], [0.09, 0.10]], 'db': [0.11, 0.12]}
}

learning_rate = 0.1
update_weights(network, gradients, learning_rate)
print("Updated Network:", network)



# Update weights with a learning rate of 0.1
update_weights(network, gradients, learning_rate=0.1)
print("Cole + Updated Network:", network)

Updated Network: {'layer1': {'weights': [[0.099, 0.198], [0.297, 0.396]], 'biases': [0.495, 0.594]}, 'layer2': {'weights': [[0.693, 0.792], [0.891, 0.99]], 'biases': [1.0890000000000002, 1.188]}}
Cole + Updated Network: {'layer1': {'weights': [[0.098, 0.196], [0.294, 0.392]], 'biases': [0.49, 0.588]}, 'layer2': {'weights': [[0.6859999999999999, 0.784], [0.882, 0.98]], 'biases': [1.0780000000000003, 1.176]}}


## Step 7: Visualizing Loss Changes

In [170]:
# Use MSE to compute the loss 
def compute_loss(y_true, y_pred):
    # provide your code
    y_true = np.array(y_true) #numpy conversions
    y_pred = np.array(y_pred) 
    
    #calculate MSE using numpy mean funct 
    mse = np.mean((y_true - y_pred)**2)  # or np.square(y_true - y_pred).mean() since they both work!

    return mse


# a good test case:
y_true = [1, 2, 3, 4, 5]
y_pred = [1.1, 1.8, 3.2, 3.9, 5.2]

loss = compute_loss(y_true, y_pred)
print(f"MSE Loss: {loss}")


y_true = np.array([1, 2, 3, 4, 5])
y_pred = np.array([1.1, 1.8, 3.2, 3.9, 5.2])

loss = compute_loss(y_true, y_pred)
print(f"MSE Loss: {loss}")

MSE Loss: 0.028000000000000032
MSE Loss: 0.028000000000000032


In [172]:
import matplotlib.pyplot as plt
import numpy as np
# Training Loop
losses = []
inputs = np.array([[0.5, 0.2, 0.1]])
y_true = np.array([[1]])
learning_rate = 0.1

for iteration in range(100):
    # provide your code
    # Hints: forward_propagation function with inputs network
    #        compute_loss for y_true and activations[-1]
    #        add loss to losses
     

    # gradients = backpropagation function
    # update_weights
    activations = forward_propagation(inputs,network)
    y_pred = activations[-1]
    loss = compute_loss(y_true, y_pred)
    #prediction is the final output 
    losses.append(loss)
    gradients = backpropagation(activities, y_true, network)
    #should give us a gradient!
    update_weights(network, gradients, learning_state)
    
# Plot Loss and rerun all cells
plt.plot(losses)
plt.title("Cole + Loss Before and After Weight Updates")
plt.xlabel("Iterations")
plt.ylabel("Loss")
plt.show()


NameError: name 'activities' is not defined

### Step 8: Visualizing Gradients Changes (Graduate students)

Please pick a weight and plot the gradient change

You need to point which weight you pick and label it on your graph.

In [ ]:
# Your code